version: "3"
services:
  redis:
    image: redis:4.0-alpine

  convertit:
     image: makinacorpus/convertit
     hostname: convertit
     # uncomment to allow containers resolve DNS if it is not public
     #extra_hosts:
     #  - "${DOMAIN_NAME}:37.187.XXX.XXX"

  screamshotter:
     image: makinacorpus/screamshotter
     environment:
       - DJANGO_SETTINGS_MODULE=screamshotter.settings
     # uncomment to allow containers resolve DNS if it is not public
     #extra_hosts:
     #  - "${DOMAIN_NAME}:37.187.XXX.XXX"
     depends_on:
       - convertit

  memcached:
    image: memcached:1.5-alpine

  celery:
    image: geotrekce/admin:${GEOTREK_VERSION}
    env_file:
      - .env
    depends_on:
      - redis
      - screamshotter
      - memcached
    volumes:
      - ./var:/app/src/var
    working_dir: /app/src
    command: celery -A geotrek worker -l warning

  web:
     image: geotrekce/admin:${GEOTREK_VERSION}
     # change port 8002 to one available
     # fix port in geotrek.nginx.conf / django upstream
     ports:
       - "127.0.0.1:8002:8000"
     env_file:
       - .env
     volumes:
      - ./var:/app/src/var
     depends_on:
       - celery
     command: gunicorn geotrek.wsgi:application -w 5 --bind 0.0.0.0:8000

  api:
     image: geotrekce/admin:${GEOTREK_VERSION}
     # change port 8001 to one available
     # fix port in geotrek.nginx.conf / api upstream
     ports:
       - "8001:8000"
     env_file:
       - .env
     volumes:
      - ./var:/app/src/var
     depends_on:
       - web
       - celery
     command: gunicorn geotrek.wsgi:application -w 5 --bind 0.0.0.0:8000

